### ISSUE TITLE
[Help] Error while load process list C#

### ISSUE THREAD

**Issue by mereketehe** [fenix01/cheatengine-library#4]
Image 1 :

http://lamberto-nababan.com/1.png

Image 2 (after click process list) :

http://lamberto-nababan.com/2.png

I got that error message, can you help me please ?

Thanks,

mereketehe

**Comment by fenix01** [comment]
Hi mereketehe,

Could you tell me how to reproduce this error ? What did you do exactly ?

And did you copy the library (ce-lib*.dll) in the executable folder of the project ?

Regards,

**Comment by mereketehe** [comment]
I use windows 7 32 bit.

When I run it from Visual Studio 2013, and I click "Process List", it shown error like picture number 2.

**Comment by fenix01** [comment]
I tried yesterday and it works perfectly.
In a first time, compile the project.
Then, copy ce-lib32.dll in .\bin\x86\Release\ or .\bin\x86\Debug
Now, launch the program with administrator rights.
Click on the button "load library" to load ce-lib32.dll and finally click on "process list" and it should work.

**Comment by mereketehe** [comment]
I have 2 questions.

1. where I should put connector.cs ? 
2. In this picture : http://s30.postimg.org/5o2ectr4x/Untitled.png . Is this configuration for 64 bit OS ? What is the configuration for 32 bit OS ?

**Comment by mereketehe** [comment]
The third question, why when I click load library it shown this : http://s30.postimg.org/awgfduuu9/Untitled2.png

**Comment by fenix01** [comment]
connector.cs should be in your source folder. Then you should import this file. On the project, right click -> add -> existing item -> select connector.cs

Yes you're right this is the configuration to compile for 64 bits. You have to select the configuration for 32 bits. To do so, look at this picture.
http://s4.postimg.org/721hnqlot/config.png

To answer to your third question, this is probably because you are using the 64 bits library and it is not support by your os which runs on 32 bits. So, use ce-lib32.dll and compile for 32 bits.
